// Regenerates the icon geometry in src/components/icons.jsx.
//
// Run it after importing a new icon name from '../components/icons': the
// script reads every icon the app imports, pulls that icon's node list out of
// the installed lucide-react-native package (ISC, © Lucide Contributors), and
// rewrites everything below the marker in icons.jsx. Nothing above the marker
// is touched.
//
//   node scripts/gen-icons.js
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const LUCIDE = path.join(ROOT, 'node_modules/lucide-react-native/dist/esm');
const ICONS_FILE = path.join(ROOT, 'src/components/icons.jsx');
const MARKER = '// --- icons below are generated by scripts/gen-icons.js ---';

function sourceFiles(dir, found = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) sourceFiles(full, found);
    else if (/\.(js|jsx)$/.test(entry.name)) found.push(full);
  }
  return found;
}

// Every icon name the app imports from the shared module.
function iconNamesInUse() {
  const names = new Set();
  const files = ['app', 'src'].flatMap((d) => sourceFiles(path.join(ROOT, d)));
  for (const file of files) {
    const src = fs.readFileSync(file, 'utf8');
    const re = /import\s*\{([^{}]*?)\}\s*from\s*'\.{1,2}\/[^']*icons'/g;
    let match;
    while ((match = re.exec(src))) {
      match[1].split(',').map((n) => n.trim()).filter(Boolean).forEach((n) => names.add(n));
    }
  }
  return [...names].sort();
}

// Exported name -> icon module, read from lucide's barrel so aliases resolve
// (AlertCircle lives in circle-alert.mjs, and so on).
function lucideModules() {
  const barrel = fs.readFileSync(path.join(LUCIDE, 'lucide-react-native.mjs'), 'utf8');
  const map = {};
  const re = /export \{([^}]*)\} from '\.\/icons\/([^']+)';/g;
  let match;
  while ((match = re.exec(barrel))) {
    for (const spec of match[1].split(',')) {
      const alias = spec.trim().replace(/^default as /, '');
      if (alias) map[alias] = match[2];
    }
  }
  return map;
}

// The [tag, attrs] array literal that follows createLucideIcon(, brackets
// balanced and quotes respected.
function nodeLiteral(src) {
  const open = src.indexOf('[', src.indexOf('createLucideIcon('));
  let depth = 0;
  let quote = null;
  for (let i = open; i < src.length; i += 1) {
    const c = src[i];
    if (quote) {
      if (c === '\\') i += 1;
      else if (c === quote) quote = null;
    } else if (c === '"' || c === "'") quote = c;
    else if (c === '[') depth += 1;
    else if (c === ']' && (depth -= 1) === 0) return src.slice(open, i + 1);
  }
  throw new Error('unbalanced icon node list');
}

const quoted = (value) => `'${String(value).replace(/'/g, "\\'")}'`;

const modules = lucideModules();
const lines = iconNamesInUse().map((name) => {
  const file = modules[name];
  if (!file) throw new Error(`lucide has no icon named ${name}`);
  const literal = nodeLiteral(fs.readFileSync(path.join(LUCIDE, 'icons', file), 'utf8'));
  const nodes = new Function(`return ${literal}`)()
    .map(([tag, attrs]) => {
      const pairs = Object.entries(attrs)
        .filter(([key]) => key !== 'key') // the renderer keys by index
        .map(([key, value]) => `${key}: ${quoted(value)}`);
      return `[${quoted(tag)}, { ${pairs.join(', ')} }]`;
    })
    .join(', ');
  return `export const ${name} = icon([${nodes}]);`;
});

const current = fs.readFileSync(ICONS_FILE, 'utf8');
const head = current.slice(0, current.indexOf(MARKER) + MARKER.length);
fs.writeFileSync(ICONS_FILE, `${head}\n${lines.join('\n')}\n`);
console.log(`wrote ${lines.length} icons to src/components/icons.jsx`);
